module Ogli
  
end

require "ogli/model"
require "ogli/fetching_array"
require "ogli/action"
require "ogli/activity"
require "ogli/address"
require "ogli/album"
require "ogli/book"
require "ogli/comment"
require "ogli/event"
require "ogli/group"
require "ogli/interest"
require "ogli/movie"
require "ogli/music"
require "ogli/note"
require "ogli/page"
require "ogli/photo"
require "ogli/post"
require "ogli/television"
require "ogli/video"
require "ogli/user"
require "ogli/client"